export const SUBJECT_ERROR_CODES = {
  SUBJECT_LIST_INVALID_QUERY: "SUBJECT_LIST_INVALID_QUERY",
  SUBJECT_CREATE_INVALID_INPUT: "SUBJECT_CREATE_INVALID_INPUT",
  SUBJECT_CREATE_NAME_EXISTS: "SUBJECT_CREATE_NAME_EXISTS",
  SUBJECT_PARAM_INVALID_ID: "SUBJECT_PARAM_INVALID_ID",
  SUBJECT_GET_NOT_FOUND: "SUBJECT_GET_NOT_FOUND",
  SUBJECT_UPDATE_INVALID_INPUT: "SUBJECT_UPDATE_INVALID_INPUT",
  SUBJECT_UPDATE_NOT_FOUND: "SUBJECT_UPDATE_NOT_FOUND",
  SUBJECT_UPDATE_NAME_EXISTS: "SUBJECT_UPDATE_NAME_EXISTS",
  SUBJECT_DELETE_NOT_FOUND: "SUBJECT_DELETE_NOT_FOUND",
  SUBJECT_DELETE_IN_USE: "SUBJECT_DELETE_IN_USE",
} as const;

export type SubjectErrorCode =
  (typeof SUBJECT_ERROR_CODES)[keyof typeof SUBJECT_ERROR_CODES];

