export const SUBJECT_ERROR_CODES = {
  SUBJECT_LIST_INVALID_QUERY: "SUBJECT_LIST_INVALID_QUERY",
  SUBJECT_CREATE_INVALID_INPUT: "SUBJECT_CREATE_INVALID_INPUT",
  SUBJECT_CREATE_NAME_EXISTS: "SUBJECT_CREATE_NAME_EXISTS",
} as const;

export type SubjectErrorCode =
  (typeof SUBJECT_ERROR_CODES)[keyof typeof SUBJECT_ERROR_CODES];
