export const PARENT_ERROR_CODES = {
  PARENT_ASSIGN_INVALID_INPUT: "PARENT_ASSIGN_INVALID_INPUT",
  PARENT_ASSIGN_STUDENT_OR_PARENT_NOT_FOUND:
    "PARENT_ASSIGN_STUDENT_OR_PARENT_NOT_FOUND",
  PARENT_ASSIGN_ALREADY_LINKED: "PARENT_ASSIGN_ALREADY_LINKED",
  PARENT_UNASSIGN_INVALID_QUERY: "PARENT_UNASSIGN_INVALID_QUERY",
  PARENT_UNASSIGN_LINK_NOT_FOUND: "PARENT_UNASSIGN_LINK_NOT_FOUND",
  PARENT_STUDENT_PARENTS_INVALID_STUDENT_ID:
    "PARENT_STUDENT_PARENTS_INVALID_STUDENT_ID",
  PARENT_STUDENT_PARENTS_INVALID_QUERY:
    "PARENT_STUDENT_PARENTS_INVALID_QUERY",
  PARENT_STUDENT_PARENTS_STUDENT_NOT_FOUND:
    "PARENT_STUDENT_PARENTS_STUDENT_NOT_FOUND",
} as const;

export type ParentErrorCode =
  (typeof PARENT_ERROR_CODES)[keyof typeof PARENT_ERROR_CODES];