export const CERTIFICATE_TYPE_ERROR_CODES = {
  // List
  CERTIFICATE_TYPE_LIST_INVALID_QUERY: "CERTIFICATE_TYPE_LIST_INVALID_QUERY",

  // Create
  CERTIFICATE_TYPE_CREATE_NAME_REQUIRED: "CERTIFICATE_TYPE_CREATE_NAME_REQUIRED",
  CERTIFICATE_TYPE_CREATE_NAME_EXISTS: "CERTIFICATE_TYPE_CREATE_NAME_EXISTS",

  // Detail
  CERTIFICATE_TYPE_DETAIL_NOT_FOUND: "CERTIFICATE_TYPE_DETAIL_NOT_FOUND",

  // Update
  CERTIFICATE_TYPE_UPDATE_NOT_FOUND: "CERTIFICATE_TYPE_UPDATE_NOT_FOUND",
  CERTIFICATE_TYPE_UPDATE_NAME_EXISTS: "CERTIFICATE_TYPE_UPDATE_NAME_EXISTS",

  // Delete
  CERTIFICATE_TYPE_DELETE_NOT_FOUND: "CERTIFICATE_TYPE_DELETE_NOT_FOUND",
  CERTIFICATE_TYPE_DELETE_IN_USE: "CERTIFICATE_TYPE_DELETE_IN_USE",
} as const;

export type CertificateTypeErrorCode = keyof typeof CERTIFICATE_TYPE_ERROR_CODES;

