export const PROFILE_APPLICATION_ERROR_CODES = {
  PROFILE_APPLICATION_LIST_INVALID_INPUT: "PROFILE_APPLICATION_LIST_INVALID_INPUT",
  PROFILE_APPLICATION_SUBMIT_STUDENT_PROFILE_NOT_FOUND: "PROFILE_APPLICATION_SUBMIT_STUDENT_PROFILE_NOT_FOUND",
  PROFILE_APPLICATION_SUBMIT_ALREADY_PENDING: "PROFILE_APPLICATION_SUBMIT_ALREADY_PENDING",
  PROFILE_APPLICATION_DETAIL_NOT_FOUND: "PROFILE_APPLICATION_DETAIL_NOT_FOUND",
  PROFILE_APPLICATION_UPDATE_NOT_FOUND: "PROFILE_APPLICATION_UPDATE_NOT_FOUND",
  PROFILE_APPLICATION_UPDATE_NOT_PENDING: "PROFILE_APPLICATION_UPDATE_NOT_PENDING",
  PROFILE_APPLICATION_UPDATE_NOT_OWNER: "PROFILE_APPLICATION_UPDATE_NOT_OWNER",
  PROFILE_APPLICATION_REVIEW_NOT_FOUND: "PROFILE_APPLICATION_REVIEW_NOT_FOUND",
  PROFILE_APPLICATION_REVIEW_ALREADY_REVIEWED: "PROFILE_APPLICATION_REVIEW_ALREADY_REVIEWED",
  PROFILE_APPLICATION_CERTIFICATES_NOT_FOUND: "PROFILE_APPLICATION_CERTIFICATES_NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
} as const;

export type ProfileApplicationErrorCode = (typeof PROFILE_APPLICATION_ERROR_CODES)[keyof typeof PROFILE_APPLICATION_ERROR_CODES];

