export const AUTH_ERROR_CODES = {
  AUTH_LOGIN_INVALID_INPUT: "AUTH_LOGIN_INVALID_INPUT",
  AUTH_LOGIN_INVALID_CREDENTIALS: "AUTH_LOGIN_INVALID_CREDENTIALS",
  AUTH_LOGIN_ACCOUNT_INACTIVE: "AUTH_LOGIN_ACCOUNT_INACTIVE",
  AUTH_CHANGE_PASSWORD_INVALID_INPUT: "AUTH_CHANGE_PASSWORD_INVALID_INPUT",
  AUTH_CHANGE_PASSWORD_WRONG_CURRENT_PASSWORD:
    "AUTH_CHANGE_PASSWORD_WRONG_CURRENT_PASSWORD",
  AUTH_CHANGE_PASSWORD_SAME_AS_CURRENT: "AUTH_CHANGE_PASSWORD_SAME_AS_CURRENT",
  AUTH_REFRESH_TOKEN_INVALID_INPUT: "AUTH_REFRESH_TOKEN_INVALID_INPUT",
  AUTH_REFRESH_TOKEN_INVALID_TOKEN: "AUTH_REFRESH_TOKEN_INVALID_TOKEN",
  AUTH_LOGOUT_INVALID_INPUT: "AUTH_LOGOUT_INVALID_INPUT",
  AUTH_LOGOUT_INVALID_TOKEN: "AUTH_LOGOUT_INVALID_TOKEN",
  AUTH_REGISTER_INVALID_INPUT: "AUTH_REGISTER_INVALID_INPUT",
  AUTH_REGISTER_USERNAME_EXISTS: "AUTH_REGISTER_USERNAME_EXISTS",
  AUTH_REGISTER_EMAIL_EXISTS: "AUTH_REGISTER_EMAIL_EXISTS",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  SERVER_MISCONFIGURATION: "SERVER_MISCONFIGURATION",
} as const;

export type AuthErrorCode =
  (typeof AUTH_ERROR_CODES)[keyof typeof AUTH_ERROR_CODES];
