export const ACCOUNT_ERROR_CODES = {
  ACCOUNT_LIST_INVALID_QUERY: "ACCOUNT_LIST_INVALID_QUERY",
  ACCOUNT_LIST_LEGACY_ROLE_FILTER_UNSUPPORTED: "ACCOUNT_LIST_LEGACY_ROLE_FILTER_UNSUPPORTED",
  ACCOUNT_CREATE_INVALID_INPUT: "ACCOUNT_CREATE_INVALID_INPUT",
  ACCOUNT_CREATE_USERNAME_EXISTS: "ACCOUNT_CREATE_USERNAME_EXISTS",
  ACCOUNT_CREATE_EMAIL_EXISTS: "ACCOUNT_CREATE_EMAIL_EXISTS",
} as const;

export type AccountErrorCode =
  (typeof ACCOUNT_ERROR_CODES)[keyof typeof ACCOUNT_ERROR_CODES];
