export const ACCOUNT_ERROR_CODES = {
  ACCOUNT_LIST_INVALID_QUERY: "ACCOUNT_LIST_INVALID_QUERY",
  ACCOUNT_LIST_LEGACY_ROLE_FILTER_UNSUPPORTED: "ACCOUNT_LIST_LEGACY_ROLE_FILTER_UNSUPPORTED",
  ACCOUNT_CREATE_INVALID_INPUT: "ACCOUNT_CREATE_INVALID_INPUT",
  ACCOUNT_CREATE_USERNAME_EXISTS: "ACCOUNT_CREATE_USERNAME_EXISTS",
  ACCOUNT_CREATE_EMAIL_EXISTS: "ACCOUNT_CREATE_EMAIL_EXISTS",
  ACCOUNT_ME_NOT_FOUND: "ACCOUNT_ME_NOT_FOUND",
  ACCOUNT_DETAIL_INVALID_PARAMS: "ACCOUNT_DETAIL_INVALID_PARAMS",
  ACCOUNT_DETAIL_NOT_FOUND: "ACCOUNT_DETAIL_NOT_FOUND",
  ACCOUNT_UPDATE_INVALID_PARAMS: "ACCOUNT_UPDATE_INVALID_PARAMS",
  ACCOUNT_UPDATE_INVALID_INPUT: "ACCOUNT_UPDATE_INVALID_INPUT",
  ACCOUNT_UPDATE_NOT_FOUND: "ACCOUNT_UPDATE_NOT_FOUND",
  ACCOUNT_UPDATE_USERNAME_EXISTS: "ACCOUNT_UPDATE_USERNAME_EXISTS",
  ACCOUNT_DELETE_INVALID_PARAMS: "ACCOUNT_DELETE_INVALID_PARAMS",
  ACCOUNT_DELETE_NOT_FOUND: "ACCOUNT_DELETE_NOT_FOUND",
  ACCOUNT_DELETE_IN_USE: "ACCOUNT_DELETE_IN_USE",
} as const;

export type AccountErrorCode =
  (typeof ACCOUNT_ERROR_CODES)[keyof typeof ACCOUNT_ERROR_CODES];
