export const PROFILE_ERROR_CODES = {
  PROFILE_LIST_INVALID_QUERY: "PROFILE_LIST_INVALID_QUERY",
  PROFILE_LIST_LEGACY_ROLE_FILTER_UNSUPPORTED:
    "PROFILE_LIST_LEGACY_ROLE_FILTER_UNSUPPORTED",
  PROFILE_CREATE_INVALID_INPUT: "PROFILE_CREATE_INVALID_INPUT",
  PROFILE_CREATE_ACCOUNT_NOT_FOUND: "PROFILE_CREATE_ACCOUNT_NOT_FOUND",
  PROFILE_CREATE_ALREADY_EXISTS: "PROFILE_CREATE_ALREADY_EXISTS",
  PROFILE_ME_NOT_FOUND: "PROFILE_ME_NOT_FOUND",
  PROFILE_UPDATE_FORBIDDEN_FIELD: "PROFILE_UPDATE_FORBIDDEN_FIELD",
  PROFILE_DETAIL_INVALID_PARAMS: "PROFILE_DETAIL_INVALID_PARAMS",
  PROFILE_DETAIL_NOT_FOUND: "PROFILE_DETAIL_NOT_FOUND",
  PROFILE_DETAIL_FORBIDDEN: "PROFILE_DETAIL_FORBIDDEN",
  PROFILE_UPDATE_BY_ID_INVALID_PARAMS: "PROFILE_UPDATE_BY_ID_INVALID_PARAMS",
  PROFILE_UPDATE_BY_ID_INVALID_INPUT: "PROFILE_UPDATE_BY_ID_INVALID_INPUT",
  PROFILE_UPDATE_BY_ID_NOT_FOUND: "PROFILE_UPDATE_BY_ID_NOT_FOUND",
  PROFILE_UPDATE_BY_ID_FORBIDDEN: "PROFILE_UPDATE_BY_ID_FORBIDDEN",
  PROFILE_UPDATE_BY_ID_FORBIDDEN_FIELD: "PROFILE_UPDATE_BY_ID_FORBIDDEN_FIELD",
  PROFILE_ATTENDANCE_SUMMARY_INVALID_PARAMS:
    "PROFILE_ATTENDANCE_SUMMARY_INVALID_PARAMS",
  PROFILE_ATTENDANCE_SUMMARY_INVALID_QUERY:
    "PROFILE_ATTENDANCE_SUMMARY_INVALID_QUERY",
  PROFILE_ATTENDANCE_SUMMARY_PROFILE_NOT_FOUND:
    "PROFILE_ATTENDANCE_SUMMARY_PROFILE_NOT_FOUND",
  PROFILE_ATTENDANCE_SUMMARY_FORBIDDEN: "PROFILE_ATTENDANCE_SUMMARY_FORBIDDEN",
  PROFILE_ATTENDANCE_SUMMARY_SECTION_NOT_FOUND:
    "PROFILE_ATTENDANCE_SUMMARY_SECTION_NOT_FOUND",
  PROFILE_CERTIFICATE_LIST_INVALID_PARAMS:
    "PROFILE_CERTIFICATE_LIST_INVALID_PARAMS",
  PROFILE_CERTIFICATE_LIST_INVALID_QUERY:
    "PROFILE_CERTIFICATE_LIST_INVALID_QUERY",
  PROFILE_CERTIFICATE_LIST_PROFILE_NOT_FOUND:
    "PROFILE_CERTIFICATE_LIST_PROFILE_NOT_FOUND",
  PROFILE_CERTIFICATE_LIST_FORBIDDEN: "PROFILE_CERTIFICATE_LIST_FORBIDDEN",
  PROFILE_CERTIFICATE_LINK_INVALID_PARAMS:
    "PROFILE_CERTIFICATE_LINK_INVALID_PARAMS",
  PROFILE_CERTIFICATE_LINK_INVALID_INPUT: "PROFILE_CERTIFICATE_LINK_INVALID_INPUT",
  PROFILE_CERTIFICATE_LINK_PROFILE_NOT_FOUND:
    "PROFILE_CERTIFICATE_LINK_PROFILE_NOT_FOUND",
  PROFILE_CERTIFICATE_LINK_CERTIFICATE_NOT_FOUND:
    "PROFILE_CERTIFICATE_LINK_CERTIFICATE_NOT_FOUND",
  PROFILE_CERTIFICATE_LINK_ALREADY_EXISTS: "PROFILE_CERTIFICATE_LINK_ALREADY_EXISTS",
  PROFILE_CERTIFICATE_UNLINK_INVALID_PARAMS:
    "PROFILE_CERTIFICATE_UNLINK_INVALID_PARAMS",
  PROFILE_CERTIFICATE_UNLINK_PROFILE_NOT_FOUND:
    "PROFILE_CERTIFICATE_UNLINK_PROFILE_NOT_FOUND",
  PROFILE_CERTIFICATE_UNLINK_NOT_LINKED: "PROFILE_CERTIFICATE_UNLINK_NOT_LINKED",
} as const;

export type ProfileErrorCode =
  (typeof PROFILE_ERROR_CODES)[keyof typeof PROFILE_ERROR_CODES];
