export const ATTENDANCE_DETAIL_ERROR_CODES = {
  ATTENDANCE_DETAIL_LIST_INVALID_QUERY: "ATTENDANCE_DETAIL_LIST_INVALID_QUERY",
  ATTENDANCE_DETAIL_CREATE_INVALID_INPUT: "ATTENDANCE_DETAIL_CREATE_INVALID_INPUT",
  ATTENDANCE_DETAIL_UPDATE_INVALID_INPUT: "ATTENDANCE_DETAIL_UPDATE_INVALID_INPUT",
  ATTENDANCE_DETAIL_PARAM_INVALID_ATTENDANCE_ID:
    "ATTENDANCE_DETAIL_PARAM_INVALID_ATTENDANCE_ID",
  ATTENDANCE_DETAIL_PARAM_INVALID_DETAIL_ID:
    "ATTENDANCE_DETAIL_PARAM_INVALID_DETAIL_ID",
  ATTENDANCE_DETAIL_LIST_ATTENDANCE_NOT_FOUND: "ATTENDANCE_NOT_FOUND",
  ATTENDANCE_DETAIL_CREATE_ATTENDANCE_NOT_FOUND: "ATTENDANCE_NOT_FOUND",
  ATTENDANCE_DETAIL_CREATE_ALREADY_EXISTS: "ATTENDANCE_DETAIL_EXISTED",
  ATTENDANCE_DETAIL_UPDATE_NOT_FOUND: "ATTENDANCE_DETAIL_NOT_FOUND",
} as const;

export type AttendanceDetailErrorCode =
  (typeof ATTENDANCE_DETAIL_ERROR_CODES)[keyof typeof ATTENDANCE_DETAIL_ERROR_CODES];
