export const ROOM_ERROR_CODES = {
  ROOM_LIST_INVALID_QUERY: "ROOM_LIST_INVALID_QUERY",
  ROOM_CREATE_INVALID_INPUT: "ROOM_CREATE_INVALID_INPUT",
  ROOM_AVAILABILITY_INVALID_QUERY: "ROOM_AVAILABILITY_INVALID_QUERY",
  ROOM_UPDATE_INVALID_INPUT: "ROOM_UPDATE_INVALID_INPUT",
  ROOM_PARAM_INVALID_ID: "ROOM_PARAM_INVALID_ID",
  ROOM_CREATE_NAME_EXISTS: "ROOM_CREATE_NAME_EXISTS",
  ROOM_GET_NOT_FOUND: "ROOM_GET_NOT_FOUND",
  ROOM_DELETE_HAS_SCHEDULES: "ROOM_DELETE_HAS_SCHEDULES",
} as const;

export type RoomErrorCode =
  (typeof ROOM_ERROR_CODES)[keyof typeof ROOM_ERROR_CODES];
