export const SCHEDULE_ERROR_CODES = {
  SCHEDULE_LIST_INVALID_QUERY: "SCHEDULE_LIST_INVALID_QUERY",
  SCHEDULE_CREATE_INVALID_INPUT: "SCHEDULE_CREATE_INVALID_INPUT",
  SCHEDULE_MY_LIST_INVALID_QUERY: "SCHEDULE_MY_LIST_INVALID_QUERY",
  SCHEDULE_UPDATE_INVALID_INPUT: "SCHEDULE_UPDATE_INVALID_INPUT",
  SCHEDULE_PARAM_INVALID_ID: "SCHEDULE_PARAM_INVALID_ID",
  SCHEDULE_SECTION_PARAM_INVALID_ID: "SCHEDULE_SECTION_PARAM_INVALID_ID",
  SCHEDULE_CREATE_SECTION_NOT_FOUND: "SECTION_NOT_FOUND",
  SCHEDULE_CREATE_ROOM_NOT_FOUND: "ROOM_NOT_FOUND",
  SCHEDULE_CREATE_ROOM_CONFLICT: "ROOM_SCHEDULE_CONFLICT",
  SCHEDULE_GET_NOT_FOUND: "SCHEDULE_NOT_FOUND",
  SCHEDULE_UPDATE_NOT_FOUND: "SCHEDULE_NOT_FOUND",
  SCHEDULE_UPDATE_ROOM_NOT_FOUND: "ROOM_NOT_FOUND",
  SCHEDULE_UPDATE_ROOM_CONFLICT: "ROOM_SCHEDULE_CONFLICT",
  SCHEDULE_DELETE_NOT_FOUND: "SCHEDULE_NOT_FOUND",
  SCHEDULE_MY_PROFILE_NOT_FOUND: "SCHEDULE_MY_PROFILE_NOT_FOUND",
  SCHEDULE_SECTION_NOT_FOUND: "SECTION_NOT_FOUND",
} as const;

export type ScheduleErrorCode =
  (typeof SCHEDULE_ERROR_CODES)[keyof typeof SCHEDULE_ERROR_CODES];

