export const ATTENDANCE_ERROR_CODES = {
  ATTENDANCE_LIST_INVALID_QUERY: "ATTENDANCE_LIST_INVALID_QUERY",
  ATTENDANCE_SECTION_LIST_INVALID_QUERY: "ATTENDANCE_SECTION_LIST_INVALID_QUERY",
  ATTENDANCE_CREATE_INVALID_INPUT: "ATTENDANCE_CREATE_INVALID_INPUT",
  ATTENDANCE_UPDATE_INVALID_INPUT: "ATTENDANCE_UPDATE_INVALID_INPUT",
  ATTENDANCE_PARAM_INVALID_ID: "ATTENDANCE_PARAM_INVALID_ID",
  ATTENDANCE_SECTION_PARAM_INVALID_ID: "ATTENDANCE_SECTION_PARAM_INVALID_ID",
  ATTENDANCE_CREATE_SECTION_NOT_FOUND: "SECTION_NOT_FOUND",
  ATTENDANCE_CREATE_DUPLICATE: "ATTENDANCE_EXISTED",
  ATTENDANCE_GET_NOT_FOUND: "ATTENDANCE_NOT_FOUND",
  ATTENDANCE_UPDATE_NOT_FOUND: "ATTENDANCE_NOT_FOUND",
  ATTENDANCE_UPDATE_DUPLICATE: "ATTENDANCE_EXISTED",
  ATTENDANCE_DELETE_NOT_FOUND: "ATTENDANCE_NOT_FOUND",
  ATTENDANCE_SECTION_NOT_FOUND: "SECTION_NOT_FOUND",
} as const;

export type AttendanceErrorCode =
  (typeof ATTENDANCE_ERROR_CODES)[keyof typeof ATTENDANCE_ERROR_CODES];
