export const REGISTRATION_ERROR_CODES = {
  REGISTRATION_CREATE_INVALID_INPUT: "REGISTRATION_CREATE_INVALID_INPUT",
  REGISTRATION_CREATE_STUDENT_PROFILE_NOT_FOUND: "STUDENT_PROFILE_NOT_FOUND",
  REGISTRATION_CREATE_SECTION_NOT_FOUND: "SECTION_NOT_FOUND",
  REGISTRATION_CREATE_SECTION_NOT_OPEN: "SECTION_NOT_OPEN",
  REGISTRATION_CREATE_SECTION_FULL: "SECTION_FULL",
  REGISTRATION_CREATE_ALREADY_REGISTERED: "REGISTRATION_ALREADY_REGISTERED",
} as const;

export type RegistrationErrorCode =
  (typeof REGISTRATION_ERROR_CODES)[keyof typeof REGISTRATION_ERROR_CODES];
