export const USAGE_ERROR_CODES = {
  // Query
  USAGE_LIST_INVALID_QUERY: "USAGE_LIST_INVALID_QUERY",

  // Create / Update
  USAGE_CREATE_INVALID_INPUT: "USAGE_CREATE_INVALID_INPUT",
  USAGE_UPDATE_INVALID_INPUT: "USAGE_UPDATE_INVALID_INPUT",

  // Params
  USAGE_PARAM_INVALID_ID: "USAGE_PARAM_INVALID_ID",
  USAGE_PARAM_INVALID_SECTION_ID: "USAGE_PARAM_INVALID_SECTION_ID",

  // Not found
  USAGE_GET_NOT_FOUND: "USAGE_GET_NOT_FOUND",
  USAGE_UPDATE_NOT_FOUND: "USAGE_UPDATE_NOT_FOUND",
  USAGE_DELETE_NOT_FOUND: "USAGE_DELETE_NOT_FOUND",

  // Business
  USAGE_CREATE_ROOM_NOT_FOUND: "USAGE_CREATE_ROOM_NOT_FOUND",
  USAGE_TIME_OVERLAP: "USAGE_TIME_OVERLAP",

  // Section
  USAGE_LINK_SECTION_EXISTS: "USAGE_LINK_SECTION_EXISTS",
  USAGE_LINK_SECTION_NOT_FOUND: "USAGE_LINK_SECTION_NOT_FOUND",
  USAGE_UNLINK_SECTION_NOT_LINKED: "USAGE_UNLINK_SECTION_NOT_LINKED",

  // Delete
  USAGE_DELETE_HAS_SECTIONS: "USAGE_DELETE_HAS_SECTIONS",
} as const;

export type UsageErrorCode =
  (typeof USAGE_ERROR_CODES)[keyof typeof USAGE_ERROR_CODES];

