export const SECTION_ERROR_CODES = {
  SECTION_LIST_INVALID_QUERY: "SECTION_LIST_INVALID_QUERY",
  SECTION_CREATE_INVALID_INPUT: "SECTION_CREATE_INVALID_INPUT",
  SECTION_MY_LIST_INVALID_QUERY: "SECTION_MY_LIST_INVALID_QUERY",
  SECTION_STUDENTS_INVALID_QUERY: "SECTION_STUDENTS_INVALID_QUERY",
  SECTION_UPDATE_INVALID_INPUT: "SECTION_UPDATE_INVALID_INPUT",
  SECTION_STATUS_INVALID_INPUT: "SECTION_STATUS_INVALID_INPUT",
  SECTION_VISIBILITY_INVALID_INPUT: "SECTION_VISIBILITY_INVALID_INPUT",
  SECTION_PARAM_INVALID_ID: "SECTION_PARAM_INVALID_ID",
  SECTION_GET_NOT_FOUND: "SECTION_GET_NOT_FOUND",
  SECTION_MY_LIST_LECTURER_PROFILE_NOT_FOUND:
    "SECTION_MY_LIST_LECTURER_PROFILE_NOT_FOUND",
  SECTION_STUDENTS_SECTION_NOT_FOUND: "SECTION_STUDENTS_SECTION_NOT_FOUND",
  SECTION_UPDATE_NOT_FOUND: "SECTION_UPDATE_NOT_FOUND",
  SECTION_UPDATE_LECTURER_NOT_FOUND: "SECTION_UPDATE_LECTURER_NOT_FOUND",
  SECTION_UPDATE_LECTURER_INVALID_ROLE: "SECTION_UPDATE_LECTURER_INVALID_ROLE",
  SECTION_UPDATE_MAX_CAPACITY_TOO_SMALL: "SECTION_UPDATE_MAX_CAPACITY_TOO_SMALL",
  SECTION_DELETE_NOT_FOUND: "SECTION_DELETE_NOT_FOUND",
  SECTION_DELETE_HAS_STUDENTS: "SECTION_DELETE_HAS_STUDENTS",
  SECTION_STATUS_NOT_FOUND: "SECTION_STATUS_NOT_FOUND",
  SECTION_VISIBILITY_NOT_FOUND: "SECTION_VISIBILITY_NOT_FOUND",
  SECTION_CREATE_SUBJECT_NOT_FOUND: "SECTION_CREATE_SUBJECT_NOT_FOUND",
  SECTION_CREATE_LECTURER_NOT_FOUND: "SECTION_CREATE_LECTURER_NOT_FOUND",
  SECTION_CREATE_LECTURER_INVALID_ROLE: "SECTION_CREATE_LECTURER_INVALID_ROLE",
  SECTION_CREATE_ROOM_NOT_FOUND: "SECTION_CREATE_ROOM_NOT_FOUND",
  SECTION_CREATE_SCHEDULE_CONFLICT: "SECTION_CREATE_SCHEDULE_CONFLICT",
  SECTION_CREATE_SCHEDULE_DUPLICATE: "SECTION_CREATE_SCHEDULE_DUPLICATE",
} as const;

export type SectionErrorCode =
  (typeof SECTION_ERROR_CODES)[keyof typeof SECTION_ERROR_CODES];
