export const SECTION_ERROR_CODES = {
  SECTION_LIST_INVALID_QUERY: "SECTION_LIST_INVALID_QUERY",
  SECTION_CREATE_INVALID_INPUT: "SECTION_CREATE_INVALID_INPUT",
  SECTION_CREATE_SUBJECT_NOT_FOUND: "SECTION_CREATE_SUBJECT_NOT_FOUND",
  SECTION_CREATE_LECTURER_NOT_FOUND: "SECTION_CREATE_LECTURER_NOT_FOUND",
  SECTION_CREATE_LECTURER_INVALID_ROLE: "SECTION_CREATE_LECTURER_INVALID_ROLE",
  SECTION_CREATE_ROOM_NOT_FOUND: "SECTION_CREATE_ROOM_NOT_FOUND",
  SECTION_CREATE_SCHEDULE_CONFLICT: "SECTION_CREATE_SCHEDULE_CONFLICT",
  SECTION_CREATE_SCHEDULE_DUPLICATE: "SECTION_CREATE_SCHEDULE_DUPLICATE",
} as const;

export type SectionErrorCode =
  (typeof SECTION_ERROR_CODES)[keyof typeof SECTION_ERROR_CODES];
