export const CERTIFICATE_ERROR_CODES = {
  // List
  CERTIFICATE_LIST_INVALID_QUERY: "CERTIFICATE_LIST_INVALID_QUERY",

  // Create
  CERTIFICATE_CREATE_APPLICATION_NOT_APPROVED: "CERTIFICATE_CREATE_APPLICATION_NOT_APPROVED",
  CERTIFICATE_CREATE_TYPE_NOT_FOUND: "CERTIFICATE_CREATE_TYPE_NOT_FOUND",
  CERTIFICATE_CREATE_DUPLICATE_APP_TYPE: "CERTIFICATE_CREATE_DUPLICATE_APP_TYPE",

  // Detail
  CERTIFICATE_DETAIL_NOT_FOUND: "CERTIFICATE_DETAIL_NOT_FOUND",

  // Update
  CERTIFICATE_UPDATE_NOT_FOUND: "CERTIFICATE_UPDATE_NOT_FOUND",

  // Delete
  CERTIFICATE_DELETE_NOT_FOUND: "CERTIFICATE_DELETE_NOT_FOUND",
} as const;

export type CertificateErrorCode = keyof typeof CERTIFICATE_ERROR_CODES;

